INSERT INTO TICKETS (STATUS,PRIORITY) VALUES ('Ready', 3);
INSERT INTO TICKETS (STATUS,PRIORITY) VALUES ('In-Progress', 1);
INSERT INTO TICKETS (STATUS,PRIORITY) VALUES ('Completed', 2);
INSERT INTO TICKETS (STATUS,PRIORITY) VALUES ('Re-opened', 4);
