CREATE TABLE IF NOT EXISTS TICKETS(
    ID           INTEGER(10)  PRIMARY KEY AUTO_INCREMENT NOT NULL,
    STATUS       VARCHAR(100) NOT NULL,
    PRIORITY     INTEGER (10)
    );
CREATE TABLE IF NOT EXISTS COMMENTS(
    CID         INTEGER(10)  PRIMARY KEY AUTO_INCREMENT NOT NULL,
    COMMENT     VARCHAR(100) NOT NULL,
    TID         INTEGER (10),
    DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    AUTHOR      VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS JOINERS(
    ID          INTEGER(10)  PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CID         INTEGER (10) ,
    TID         INTEGER (10),
    foreign key(CID) references COMMENTS(CID),
    foreign key(TID) references TICKETS(ID)
);